package com.medibook.enums;

public enum NotificationType {
    APPOINTMENT_BOOKED,
    APPOINTMENT_ACCEPTED,
    APPOINTMENT_REJECTED,
    APPOINTMENT_CANCELLED,
    APPOINTMENT_RESCHEDULED,
    APPOINTMENT_COMPLETED,
    NO_SHOW_DETECTED,
    REMINDER_24H,
    REMINDER_1H,
    FOLLOW_UP_REMINDER,
    SYSTEM_ANNOUNCEMENT,
    ACCOUNT_UPDATE,
    NEW_MEDICAL_RECORD,
    MEDICAL_RECORD_UPDATED
}
