package com.medibook.notification.enums;
public enum NotificationType {
    APPOINTMENT_BOOKED, APPOINTMENT_ACCEPTED, APPOINTMENT_REJECTED, APPOINTMENT_CANCELLED,
    APPOINTMENT_COMPLETED, REMINDER_24H, REMINDER_1H, SYSTEM_MESSAGE, REVIEW_RECEIVED,
    VERIFICATION_UPDATE
}
